// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///  import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ``
class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSzC_bsCARwdAgcad0qUXQ7B_dfWQeSkM',
    appId: '1:410983318810:web:21831dc3de639b2bf518a3',
    messagingSenderId: '410983318810',
    projectId: 'formapp-fd78f',
    authDomain: 'formapp-fd78f.firebaseapp.com',
    storageBucket: 'formapp-fd78f.appspot.com',
    measurementId: 'G-HHBF24L2L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP7GiF7GUR6GR74OqgMVD-TKiZsZHSauE',
    appId: '1:410983318810:android:814e99c1bc070144f518a3',
    messagingSenderId: '410983318810',
    projectId: 'formapp-fd78f',
    storageBucket: 'formapp-fd78f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqJw2kEPRkZOy9vLqR3bigUU-paaK1xys',
    appId: '1:410983318810:ios:6b030855ebd487a2f518a3',
    messagingSenderId: '410983318810',
    projectId: 'formapp-fd78f',
    storageBucket: 'formapp-fd78f.appspot.com',
    iosBundleId: 'com.example.formapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqJw2kEPRkZOy9vLqR3bigUU-paaK1xys',
    appId: '1:410983318810:ios:f0e87c9d4437b2a0f518a3',
    messagingSenderId: '410983318810',
    projectId: 'formapp-fd78f',
    storageBucket: 'formapp-fd78f.appspot.com',
    iosBundleId: 'com.example.formapp.RunnerTests',
  );
}
